- name: Download and add key to sign nginx packages
  apt_key: 
    url: http://nginx.org/keys/nginx_signing.key
    state: present
  become: yes

- name: Entry in sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: '{{ item }}'
  with_items:
    - deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx
    - deb-src http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx 
  become: yes
  register: repo_status

- name: update apt and install nginx and its dependencies
  apt:
    update_cache: yes
    name: '{{ item }}'
    state: present
  with_items:
    - nginx
    - git
    - libpcre3-dev 
    - libssl-dev
    - build-essential
  become: yes
  when: repo_status.changed

- name: Record precompiled modules of nginx
  # shell: python -c "import commands; print(commands.getoutput('nginx -V').split('\n')[4].split(':')[1])"
  shell: nginx -V 2>&1  >/dev/null | grep -Po  "\-\-prefix=/.*"
  register: precompiled_modules

- name: Record nginx version
  # shell: python -c "import commands; print(commands.getoutput('nginx -v').split(':')[1].split('/')[1])"
  shell: nginx -v 2>&1 >/dev/null | cut -d ":" -f2 | cut -d "/" -f2
  register: nginx_version

- name: download source code of nginx
  get_url:
    url: http://nginx.org/download/nginx-{{ nginx_version.stdout }}.tar.gz
    dest: /opt/
  become: yes

- name: Extract the source code folder
  unarchive:
    src: /opt/nginx-{{ nginx_version.stdout }}.tar.gz
    dest: /opt/
    remote_src: yes
  become: yes

- name: Download the nginx-more-headers-module
  git:
    repo: https://github.com/openresty/headers-more-nginx-module.git
    dest: /opt/headers-more-nginx-module
  become: yes

- name: Complile source code with dynamic module
  shell: cd /opt/nginx-{{ nginx_version.stdout }} && sudo ./configure --add-dynamic-module=../headers-more-nginx-module {{ precompiled_modules.stdout }}

- name: Make modules
  make:
    chdir: /opt/nginx-{{ nginx_version.stdout }}
    target: modules
  become: yes

- name: Copy new module in nginx dir
  copy:
    src: /opt/nginx-{{ nginx_version.stdout }}/objs/ngx_http_headers_more_filter_module.so
    dest: /etc/nginx/modules
    remote_src: yes
  become: yes

- name: Add module path in nginx.conf
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: 'pid        /var/run/nginx.pid;'
    line: 'load_module modules/ngx_http_headers_more_filter_module.so;'
  become: yes
  
- name: Add server name config in nginx.conf
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: 'access_log  /var/log/nginx/access.log  main;'
    line: '{{ item }}'
  with_items:
    - server_tokens off;
    - "more_set_headers 'Server: {{ server_name }}';"
  become: yes
  
- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: yes